### ISSUE TITLE
 "スタッフID かつ 今日の日付" のレコードに行くボタンを設置

### ISSUE THREAD

**Issue by ShumpeiYamauchi** [ShumpeiYamauchi/test_attendance_FM#14]
出勤時間のみを入力したレコードに行きやすいようにホーム画面に "スタッフ ID x 今日の日付" のレコードに行くボタンを設置する。

### Todo
- [x] 入力ダイアログについて調べる
- [x] スタッフID を入力し、その ID の今日のレコードに移動。もし、該当レコードがなければ、その ID で今日のレコードを新規作成

- [x] 月別レコードに関しても同様のボタンを作成する

**Comment by ShumpeiYamauchi** [comment]
- ID 入力で今日のレコードにいく or 新規作成するスクリプト
![スクリーンショット 2021-04-26 9 57 00](https://user-images.githubusercontent.com/81791228/116015871-d6334200-a675-11eb-991c-8c736baeb065.png)

- 実際の ID 入力画面
<img width="1021" alt="スクリーンショット 2021-04-26 9 57 16" src="https://user-images.githubusercontent.com/81791228/116015926-011d9600-a676-11eb-9e1a-553012939a41.png">

**Comment by ShumpeiYamauchi** [comment]
月別集計に関しても同様のものを設置。
![スクリーンショット 2021-04-26 10 00 17](https://user-images.githubusercontent.com/81791228/116015984-37f3ac00-a676-11eb-9c72-a2005d19336a.png)

**Comment by ShumpeiYamauchi** [comment]
（FM スクリプトのテキストとしてのコピペってどうするんだろう……）

**Comment by hi-noguchi** [comment]
> （FM スクリプトのテキストとしてのコピペってどうするんだろう……）

デザインレポートから取ってくるか、MBS Plugin 使うのどちらかですねー。
https://www.monkeybreadsoftware.com/filemaker/
